---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  # Triggers the workflow on push events but only for specified branches
  push:
    branches:
      - dev # Replace with your default branch if different
      - prod
  pull_request:
    branches: 
      - dev
      - prod

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
        with:
          working_directory: "collections/ansible_collections/sample_namespace/sample_collection"
          args: "--exclude extensions/"
